apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: nirav1611/frontend-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: staging
spec:
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
